name: Continuous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache nodemodules
        id: cache
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: node-modules-cache

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: cd backend && npm i

      - name: Build
        run: cd backend && npm run build

      - name: Generate Artifact
        run: cd backend/build && zip -r backendartifact.zip ./ -x '*.git*'

      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifact
          path: backend/build/backendartifact.zip

  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache nodemodules
        id: cache
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: node-modules-cache

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd backend && npm i

      - name: Lint the code
        run: cd backend && npm run lint

  tests:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache nodemodules
        id: cache
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: node-modules-cache

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd backend && npm i

      - name: Test the code
        run: cd backend && npm t

  static-analysis:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          language: javascript

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: cd backend && npm i

      - name: Build
        run: cd backend && npm run build

      - name: Perform CodeQL Analysis
        run: github/codeql-action/analyze@v2
        with:
          category: "/language:javascript"

  security-audit:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for security issues
        run: cd backend && npm audit --audit-level=medium
