name: Continuous Integration
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: check node version
        run: node -v
      - run: cd backend && npm i
      - run: cd backend && npm run build
